[package]
name = "twitter-cron"
version = "0.1.0"
edition = "2021"

[dependencies]
oauth = "0.0.1"
tokio = { version = "1", features = ["full"] }
tokio-cron-scheduler = "0.13"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
